service: telegram-bot-serverless
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 128 # in MB
  environment:
    TELEGRAM_BOT_TOKEN: ${env:TELEGRAM_BOT_TOKEN}

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /
          method: post
          cors: true

plugins:
  - serverless-plugin-typescript